version: '3.9'

services:
  storems:
    build: ./storems
    container_name: storems
    volumes:
      - ./storems:/app
    ports:
      - '8000:8000'
    depends_on:
      - store_db
    env_file:
      - .env

  test:
    build: ./storems
    command: pytest -q
    profiles:
    - test
    working_dir: /app
    volumes:
      - ./storems:/app
    env_file:
      - .env
    depends_on:
      store_db:
        condition: service_healthy

  store_db:
    image: mysql:8
    container_name: store_db
    environment:
      MYSQL_DATABASE: ${STORE_DB_NAME}
      MYSQL_USER: ${STORE_DB_USER}
      MYSQL_PASSWORD: ${STORE_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - store_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - storems

volumes:
  store_db_data:
