version: '3.9'

services:
  storems:
    build: ./storems
    container_name: storems
    volumes:
      - ./storems:/app
    ports:
      - '8000:8000'
    depends_on:
      - store_db
    env_file:
      - .env

  store_db:
    image: mysql:8
    container_name: store_db
    environment:
      MYSQL_DATABASE: ${STORE_DB_NAME}
      MYSQL_USER: ${STORE_DB_USER}
      MYSQL_PASSWORD: ${STORE_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - store_db_data:/var/lib/mysql

volumes:
  store_db_data:
