# Generated by Django 3.2.25 on 2026-04-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('pago_diario', models.IntegerField(default=0, help_text='Monto acordado por día trabajado')),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Referencia de cuándo comenzaron a trabajar juntos')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'db_table': 'personal',
            },
        ),
    ]
