# Generated by Django 3.2.25 on 2026-01-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_asistencia_pago'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='horarios.horariosemanal')),
            ],
            options={
                'unique_together': {('horario', 'dia')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horarios.diahorario')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.empleado')),
            ],
            options={
                'unique_together': {('dia', 'empleado')},
            },
        ),
    ]
