# Generated by Django 3.2.25 on 2026-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_asignaciondia_diahorario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosemanal',
            name='admin_id',
            field=models.IntegerField(db_index=True, default=999),
        ),
    ]
