# Generated by Django 3.2.25 on 2026-01-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_horariosemanal_admin_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariosemanal',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios'},
        ),
        migrations.AlterModelTable(
            name='horariosemanal',
            table='horario',
        ),
    ]
