# Generated by Django 3.2.25 on 2026-01-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_auto_20260104_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosemanal',
            name='admin_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddConstraint(
            model_name='horariosemanal',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('admin_id',), name='unique_active_horario_per_admin'),
        ),
    ]
