# Generated by Django 3.2.25 on 2026-01-20 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20260117_2310'),
        ('horarios', '0005_auto_20260118_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignaciondia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado'),
        ),
    ]
