# Generated by Django 3.2.25 on 2026-04-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField(db_index=True)),
                ('nombre_nota', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notas',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
            },
        ),
    ]
