# Generated by Django 3.2.25 on 2026-04-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='admin_id',
        ),
    ]
