# Generated by Django 3.2.25 on 2026-04-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='correo@ejemplo.cl', max_length=50, null=True),
        ),
    ]
