# Generated by Django 3.2.25 on 2026-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='admin_id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.TextField(blank=True, default='Sin categoria', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
